= Example Books API Guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[introduction]
= Introduction

An example Groovy &amp; Gradle based Ratpack app.

This app demonstrates

* Metrics
* Authentication
* Blocking I/O
* Async external HTTP requests
* RxJava integration
* Hystrix integration
* WebSockets
* Async logging
* External configuration
* Request logging

Setup
-----

This application integrates with http://isbndb.com/account/logincreate[ISBNdb] and as such you will need to create a free
account and api key in order to run the application successfully.  And at the moment to run the integration tests too.

When you have done this simply add your api key to the property `isbndb.apikey` in the `application.properties` file.

[[overview-http-verbs]]
== HTTP verbs

Example Books defines HTTP verbs for all endpoints as follows:

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PUT`
| Used to update an existing resource, see endpoint for specifics

| `PATCH`
| Currently not supported

| `DELETE`
| Used to delete a resource
|===

[[resources]]
= Resources

include::resources/books.adoc[]
